name: 部署文档

on:
  push:
    branches:
      - main
  schedule:
    # Run every 2 hours between 8 AM and 8 PM CST (China Standard Time)
    - cron: '0 0-12/2 * * *' # 每天的中国时间上午8点到晚上8点（CST）

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      # Set the timezone to China Standard Time (CST)
      - name: 设置中国时区
        run: |
          sudo timedatectl set-timezone Asia/Shanghai

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Step to install cheerio before executing spider.js
      - name: 安装 cheerio
        run: |
          npm install axios
          npm install cheerio

      - name: 执行 spider 目录下的 爬虫
        run: |
          node spider/spider.js

      # Step to move markdown files from spider directory to post directory
      - name: 移动 markdown 文件到 post 目录
        run: |
          mv spider/*.md src/posts/

      # Step to commit and push changes after moving markdown files
      - name: 提交更改并推送到仓库
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/posts/*.md
          git commit -m "更新爬虫生成的 markdown 文件"
          git push origin main

      - name: 安装依赖
        run: |
          corepack enable
          npm ci

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 部署文档
          branch: gh-pages
          folder: src/.vuepress/dist
